#server:
#  port: 80
#
#eureka:
#  client:
#  registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
#  fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
#  serviceUrl:
#    defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/


server:
  port: 80 # 服务端口


eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将自已注册到Eureka服务中
    fetchRegistry: true # 服务发现，false表示自己不从Eureka服务中获取注册信息
    serviceUrl: # Eureka客户端与Eureka服务端的交互地址，集群版配置对方的地址，单机版配置自己（如果不配置则默认本机8761端口）
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/